//FIREBASE SCORE INPUT
import { initializeApp } from "https://www.gstatic.com/firebasejs/11.6.1/firebase-app.js";
import { getAnalytics } from "https://www.gstatic.com/firebasejs/11.6.1/firebase-analytics.js";
import { getDatabase } from "https://www.gstatic.com/firebasejs/11.6.1/firebase-database.js";
import { ref, set, query, orderByChild, limitToLast, get, child } from "https://www.gstatic.com/firebasejs/9.6.1/firebase-database.js";
const FB_GAMECONFIG = {
    apiKey: "AIzaSyCd2Z_1nM5CI6l6NVOrvlN7EDbKEaSTiv0",
    authDomain: "comp-2025-mio-hoffman.firebaseapp.com",
    databaseURL: "https://comp-2025-mio-hoffman-default-rtdb.firebaseio.com",
    projectId: "comp-2025-mio-hoffman",
    storageBucket: "comp-2025-mio-hoffman.firebasestorage.app",
    messagingSenderId: "724400775542",
    appId: "1:724400775542:web:dccd0b43fb6bc612725a57",
    measurementId: "G-GYKCG77RCD"
  };

const COL_C = 'white';	    // These two const are part of the coloured
const COL_B = '#CD7F32';	//  console.log for functions scheme
console.log('%c fb_io.mjs',
            'color: blue; background-color: white;');

var FB_GAMEDB

function fb_initialise() {
    console.log('%c fb_initialise(): ', 
                'color: ' + COL_C + '; background-color: ' + COL_B + ';');
                
                const FB_GAMEAPP = initializeApp(FB_GAMECONFIG);
                FB_GAMEDB  = getDatabase(FB_GAMEAPP);
                console.info(FB_GAMEDB);  
                
                const app = initializeApp(FB_GAMECONFIG);
                const analytics = getAnalytics(app);
}

fb_initialise();

function appleAttackScoreRec(){
    const uid = localStorage.getItem("userUid");
    const appleAttackScore = localStorage.getItem("appleAttackUserScore");

    const appleAttackScorePath = "gameScores/" + uid + "/appleAttack/score";
    var reference = ref(FB_GAMEDB, appleAttackScorePath);
    set(reference, appleAttackScore).then(() => {
        console.log("Userscore write rec for Apple Attack successful");
    }).catch((error) => {
        console.log(error);
    });
}

appleAttackScoreRec();

function aa_readSorted(){
    const uid = localStorage.getItem("userUid");
    let userName;
    //THE FOLLOWING CODE WAS GENERATED BY CHATGPT
      async function fetchUserName() {
    const snap = await get(child(ref(FB_GAMEDB), `gameScores/${uid}/appleAttack/userName`));

    userName = snap.exists() ? snap.val() : null;  // assign to the variable
    console.log("userName =", userName);
  }

  // call it
  fetchUserName().catch(console.error);
  //END OF CODE GENERATED BY CHATGPT

    const whereToReadFrom = "gameScores";
    const sortkey = "appleAttack/score";
    const numberToRead = 5;

    const reference = query(ref(FB_GAMEDB, whereToReadFrom), orderByChild(sortkey), limitToLast(numberToRead));
    get(reference).then((snapshot) => {
        var fb_data = snapshot.val();
        console.log(fb_data);
      if (fb_data != null) {
            console.log("Sort read success");
            const finalScore = [];
            //Following code was written by ChatGPT
            snapshot.forEach(childSnap => {
                const entry = childSnap.child("appleAttack").val(); // {score, userName}
                finalScore.push(entry);
            });
            finalScore.reverse();
            //End of code written by Chatgpt

            var firstPlace = document.getElementById("first_place");
            firstPlace.innerHTML = "1. " + finalScore[0].userName + ": " + finalScore[0].score;

            var secondPlace = document.getElementById("second_place");
            secondPlace.innerHTML = "2. " + finalScore[1].userName + ": " + finalScore[1].score;

            var thirdPlace = document.getElementById("third_place");
            thirdPlace.innerHTML = "3. " + finalScore[2].userName + ": " + finalScore[2].score;

            var fourthPlace = document.getElementById("fourth_place");
            fourthPlace.innerHTML = "4. " + finalScore[3].userName + ": " + finalScore[3].score;

            var fifthPlace = document.getElementById("fifth_place");
            fifthPlace.innerHTML = "5. " + finalScore[4].userName + ": " + finalScore[4].score;
        } else {
            console.log("Success: Record not found");
        }
    }).catch((error) => {
        console.log(error);
    });
}

aa_readSorted();