/************************************/
// gtn.mjs
//
// Written by Mio Hoffman, Term 1, 2026
//  gets the user's guess from an html form
// checks if their guess is the number generated by the computer
// turns incorrect guesses red on their screen
// validates their guesses
// alerts the user on how close their guess is to the correct number
/************************************/

//IMPORTING FIREBASE FUNCTIONS
import { ref, set, get, update, onValue, remove, onDisconnect, onChildRemoved } from "https://www.gstatic.com/firebasejs/11.6.1/firebase-database.js";

//IMPORTING VARIABLES NEEDED
import { fb_gamedb } from "./fb_io.mjs";
import { userUid } from "./fb_io.mjs";

//GLOBAL VARIABLES
var correctAnswer;
var gameRoomID;
var whichPlayer;
var score = 0;
var leavingLobby = false;

//This function:
//Gets the first player to generate a correct answer which stores in firebase
//Allows the first player to guess first
//Doesn't allow the second player to guess at the start
//Assigns the gameRoomID to the same data but in differing ways based on whether or not the player is the first player or not
function gameStart() {
    var playerPath = "gameRoom/GTN/" + userUid + "/firstPlayer";
    const dbReference = ref(fb_gamedb, playerPath);
    get(dbReference).then((snapshot) => {
        var fb_data = snapshot.val();
        if (fb_data != null) {
            if (fb_data == userUid) {
                gameRoomID = userUid;
                whichPlayer = "first";
                console.log("You are the " + whichPlayer + " player!");

                getNumber();
                disconnect();
                displaySecondPlayerUsername();
                checkFirstPlayerTurn();
            }
        } else {
            gameRoomID = sessionStorage.getItem("gameRoomCode");
            whichPlayer = "second";
            console.log("You are the " + whichPlayer + " player!");

            disconnect();
            displayFirstPlayerUsername();
            getCorrectAnswer();
            checkSecondPlayerTurn();
        }
        otherUserDisconnected();
    }).catch((error) => {
        console.log(error);
    });
}

function disconnect() {
    var gameRoomPath = "/gameRoom/GTN/" + gameRoomID;
    onDisconnect(ref(fb_gamedb, gameRoomPath)).remove()
}

function otherUserDisconnected(){
    const dbReference = ref(fb_gamedb, "/gameRoom/GTN");
    onChildRemoved(dbReference, (snapshot) => {
        var lobbyName = snapshot.key;

        if (leavingLobby == true){
            console.log("Game is over");
        }
        else {
            if (lobbyName == gameRoomID){
            alert("Sorry! Looks like your opponent left the lobby! Sending you back to the game selection page :D");
            window.location.href = "gameSelection.html";
        }
        }
    });
}

function displayFirstPlayerUsername() {
    var firstPlayerUsernamePath = "/gameRoom/GTN/" + gameRoomID + "/firstPlayerUsername"; 
    const dbReference = ref(fb_gamedb, firstPlayerUsernamePath);
    get(dbReference).then((snapshot) => {
        var fb_data = snapshot.val();
        if (fb_data != null) {
            var firstPlayerUsername = fb_data;
            var opponentUsername = document.getElementById("opponentUsername");
            opponentUsername.innerHTML = "You are playing against: " + firstPlayerUsername;
        } else {
            alert("It seems your opponent's username couldn't display! Keep playing anyway :)");
        }
    }).catch((error) => {
        console.log(error);
    });
}

function displaySecondPlayerUsername() {
    var secondPlayerUsernamePath = "/gameRoom/GTN/" + gameRoomID + "/secondPlayerUsername"; 
    const dbReference = ref(fb_gamedb, secondPlayerUsernamePath);
    get(dbReference).then((snapshot) => {
        var fb_data = snapshot.val();
        if (fb_data != null) {
            var secondPlayerUsername = fb_data;
            var opponentUsername = document.getElementById("opponentUsername");
            opponentUsername.innerHTML = "You are playing against: " + secondPlayerUsername;
        } else {
            alert("It seems your opponent's username couldn't display! Keep playing anyway :)");
        }
    }).catch((error) => {
        console.log(error);
    });
}

//This function generates the answer for the users to guess
//It stores it into firebase so both users have the same number
function getNumber() {
    correctAnswer = Math.floor(Math.random() * 20) + 1;

    //Writing the correct answer into the database so both players have the same answer
    var correctAnswerData = { "correctAnswer": correctAnswer }
    var correctAnswerPath = "/gameRoom/GTN/" + userUid;
    const dbReference = ref(fb_gamedb, correctAnswerPath);
    update(dbReference, correctAnswerData).then(() => {
        console.log("Correct number is in the database!");
    }).catch((error) => {
        console.log(error);
    });
}

//Second player getting the correct answer from the database
function getCorrectAnswer() {
    var readPath = "/gameRoom/GTN/" + gameRoomID + "/correctAnswer";
    const dbReference = ref(fb_gamedb, readPath);
    get(dbReference).then((snapshot) => {
        var fb_data = snapshot.val();
        if (fb_data != null) {
            correctAnswer = fb_data;
        } else {
            console.log("No record found!");
        }
    }).catch((error) => {
        console.log(error);
    });
}

//This function checks if it's the first player's turn
//It does this by reading the playerTurn key in the database
function checkFirstPlayerTurn() {
    var monitorPath = "/gameRoom/GTN/" + gameRoomID + "/playerTurn";
    const dbReference = ref(fb_gamedb, monitorPath);
    onValue(dbReference, (snapshot) => {
        var fb_data = snapshot.val();
        if (fb_data != null) {
            if (fb_data == 'first') { //If firebase says it's the first player's turn...
                yourTurn(); //The turn function is called
            }
            else if (fb_data == 'second') { //If it's actually the second player's turn...
                notYourTurn(); //The function for when it's not the user's turn gets called.
            }
        } else {
            console.log("No record found!");
        }
    });
}

//This function checks if it's the second player's turn
//It does this by reading the playerTurn key in the database
function checkSecondPlayerTurn() {
    var monitorPath = "/gameRoom/GTN/" + gameRoomID + "/playerTurn";
    const dbReference = ref(fb_gamedb, monitorPath);
    onValue(dbReference, (snapshot) => {
        var fb_data = snapshot.val();
        if (fb_data != null) {
            if (fb_data == "second") {
                yourTurn();
            }
            else if (fb_data == "first") {
                notYourTurn();
            }
        } else {
            console.log("No record found!");
        }
    });
}

//This function switches which player's turn it is once a player finishes their turn
function switchPlayerTurn() {
    var playerTurnPath = "/gameRoom/GTN/" + gameRoomID + "/playerTurn";
    var updatePath = "/gameRoom/GTN/" + gameRoomID;
    const dbReference = ref(fb_gamedb, playerTurnPath); //It's reading the playerTurn key in firebase
    get(dbReference).then((snapshot) => {
        var fb_data = snapshot.val();
        if (fb_data != null) {
            if (fb_data == "first") { //If it was the first player's turn
                var second = { playerTurn: "second" };
                const dbReference = ref(fb_gamedb, updatePath); //The computer updates the playerTurn to be the second player's turn
                update(dbReference, second).then(() => {
                }).catch((error) => {
                    console.log(error);
                });
            }
            else if (fb_data == "second") { //If it was the second player's turn
                var first = { playerTurn: "first" };
                const dbReference = ref(fb_gamedb, updatePath); //The computer updates the playerTurn to be the first player's turn
                update(dbReference, first).then(() => {
                }).catch((error) => {
                    console.log(error);
                });
            }
        } else {
            console.log("No record found!");
        }
    }).catch((error) => {
        console.log(error);
    });
}

//This function allows the user to guess if it is their turn
function yourTurn() {
    checkIfYouLost();
    var guessDisplay = document.getElementById("guessDisplay");
    guessDisplay.style.display = "block";
}

//This function hides the form to guess if it is not their turn so they cannot guess
function notYourTurn() {
    var guessDisplay = document.getElementById("guessDisplay");
    guessDisplay.style.display = "none";
}

//This function gets the user's guess from the html form and determines whether it is right or wrong
function getGuess() {
    score = score + 1;
    //Gets the user's guess from the html form
    var guess = document.getElementById("guess");
    guess = guess.value;

    //If the user guesses the correct answer, they get an alert saying they've got it right
    if (guess == correctAnswer) {
        leavingLobby = true;
        whoWon();
        storeUserScore();
    }
    //If their guess is zero or a negative number, they get an alert
    else if (guess <= 0) {
        alert("Put in a number between 1 and 20!");
    }
    //If their guess is higher than 20 (the max guess value), they get an alert
    else if (guess > 20) {
        alert("Put in a number between 1 and 20!")
    }
    //If their guess is smaller than the correct answer, they get an alert saying the correct number is higher
    else if (guess < correctAnswer) {
        alert("The number is higher!");
        var wrong = document.getElementById(guess);
        wrong.style.color = 'rgb(170, 0, 0)';
    }
    //If their guess is larger than the correct answer, they get an alert saying the number is lower
    else if (guess > correctAnswer) {
        alert("The number is lower!");
        wrong = document.getElementById(guess);
        wrong.style.color = 'rgb(170, 0, 0)';
    }

    switchPlayerTurn(); // After the player has inputted a guess, the computer switches whose turn it is
}

//This function inputs the player who won into the database
//It gets called when a player guesses the correct answer
//The whichPlayer variable is read to see if the user who won was the first or second player
function whoWon() {
    var playerWhoWonPath = "/gameRoom/GTN/" + gameRoomID;
    if (whichPlayer == "first") {
        let playerWhoWon = { "playerWhoWon": "first" };
        const dbReference = ref(fb_gamedb, playerWhoWonPath);
        update(dbReference, playerWhoWon).then(() => {
            console.log("First player won!");
        }).catch((error) => {
            console.log(error);
        });
    }
    else if (whichPlayer == "second") {
        let playerWhoWon = { "playerWhoWon": "second" };
        const dbReference = ref(fb_gamedb, playerWhoWonPath);
        update(dbReference, playerWhoWon).then(() => {
            console.log("Second player won!");
        }).catch((error) => {
            console.log(error);
        });
    }
}

//This function checks which player lost by using an onValue listener
function checkIfYouLost() {
    let checkWinningPlayerPath = "/gameRoom/GTN/" + gameRoomID + "/playerWhoWon";
    const dbReference = ref(fb_gamedb, checkWinningPlayerPath);
    onValue(dbReference, (snapshot) => {
        var fb_data = snapshot.val();
        if (fb_data != null) {
            if (fb_data == "first" && whichPlayer == "second") {
                gameDone();
                window.location.href = "gtnLoseScreen.html";
            }
            if (fb_data == "second" && whichPlayer == "first") {
                gameDone();
                window.location.href = "gtnLoseScreen.html";
            }
        } else {
            console.log("No one has won yet!");
        }
    });
}

//This function stores the user's score under their username in gameScores
function storeUserScore() {
    let username;
    var userNamePath = "/userData/" + userUid + "/Username";
    const dbReference = ref(fb_gamedb, userNamePath);
    get(dbReference).then((snapshot) => {
        var fb_data = snapshot.val();
        if (fb_data != null) {
            username = fb_data;
            let gtnGameScoresPath = "/gameScores/GTN/" + username;
            let userScoreData = { "score": score };
            const dbReference2 = ref(fb_gamedb, gtnGameScoresPath);
            update(dbReference2, userScoreData).then(() => {
                console.log("User score is saved!");
                window.location = "gtnWinScreen.html";
            }).catch((error) => {
                console.log(error);
            });
        } else {
            console.log("Username was not found!");
        }
    }).catch((error) => {
        console.log(error);
    });
}

//This function deletes the lobby when the game is done
//It gets called after a user wins and a user loses
function gameDone() {
    var deleteLobbyPath = "/gameRoom/GTN/" + gameRoomID;
    const dbReference = ref(fb_gamedb, deleteLobbyPath);
    remove(dbReference).then(() => {
        console.log("Lobby has been deleted!");
    }).catch((error) => {
        console.log(error);
    });
}

//EXPORT FUNCTIONS
export {
    gameStart, getNumber, getGuess
}